import forms from '@tailwindcss/forms';
import containerQueries from '@tailwindcss/container-queries';

/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'outline-variant': '#c3c6d7',
        'on-tertiary-fixed': '#001e2c',
        'surface-container-low': '#f2f4f6',
        'primary': '#004ac6',
        'error': '#ba1a1a',
        'surface-dim': '#d8dadc',
        'on-primary-fixed-variant': '#003ea8',
        'on-tertiary-container': '#e1f2ff',
        'on-tertiary-fixed-variant': '#004c69',
        'surface-container-high': '#e6e8ea',
        'primary-container': '#2563eb',
        'on-secondary': '#ffffff',
        'surface-tint': '#0053db',
        'primary-fixed': '#dbe1ff',
        'on-error': '#ffffff',
        'inverse-primary': '#b4c5ff',
        'outline': '#737686',
        'on-surface-variant': '#434655',
        'secondary-fixed': '#eaddff',
        'secondary-fixed-dim': '#d2bbff',
        'error-container': '#ffdad6',
        'on-tertiary': '#ffffff',
        'surface-container-lowest': '#ffffff',
        'secondary-container': '#8a4cfc',
        'on-primary-fixed': '#00174b',
        'tertiary-fixed': '#c4e7ff',
        'primary-fixed-dim': '#b4c5ff',
        'tertiary-fixed-dim': '#7bd0ff',
        'on-error-container': '#93000a',
        'surface-bright': '#f7f9fb',
        'on-secondary-container': '#fffbff',
        'on-primary-container': '#eeefff',
        'surface-variant': '#e0e3e5',
        'on-secondary-fixed-variant': '#5a00c6',
        'on-background': '#191c1e',
        'on-secondary-fixed': '#25005a',
        'surface-container': '#eceef0',
        'secondary': '#712ae2',
        'on-surface': '#191c1e',
        'inverse-surface': '#2d3133',
        'surface': '#f7f9fb',
        'surface-container-highest': '#e0e3e5',
        'background': '#f7f9fb',
        'tertiary-container': '#00759f',
        'tertiary': '#005b7c',
        'on-primary': '#ffffff',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'container-max': '1280px',
        'gutter': '24px',
        'section-padding': '96px',
        'margin-desktop': '48px',
        'base': '8px',
        'margin-mobile': '16px',
      },
      fontFamily: {
        'body-lg': ['Inter'],
        'display-lg-mobile': ['Inter'],
        'display-lg': ['Inter'],
        'label-sm': ['Inter'],
        'label-md': ['Inter'],
        'headline-xl': ['Inter'],
        'headline-lg': ['Inter'],
        'body-md': ['Inter'],
      },
      fontSize: {
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'display-lg-mobile': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-lg': ['64px', { lineHeight: '72px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '600' }],
        'label-md': ['14px', { lineHeight: '20px', fontWeight: '500' }],
        'headline-xl': ['36px', { lineHeight: '44px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-lg': ['30px', { lineHeight: '38px', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
      },
    },
  },
  plugins: [forms, containerQueries],
};
